//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TMA3
{
    public partial class About
    {
        protected global::System.Web.UI.WebControls.Label numberInCart;
    }
}
